#! /bin/bash

if [ -z "$1" ]; then
  echo "Usage: $(basename $0) <dirname>"
  exit 1
fi

DIR=$1

for d in src include; do
	mkdir -p $DIR/$d;
done

cat > $DIR/.gitignore << EOF
a.out
.DS_Store
*.pdf
*.swp
*.o
*.a
*.*-e
*.d
*.dSYM
*/obj
EOF
