#!/bin/bash

# Notice that required and forbidden functions are looked up the binary (man nm), not in the source files. 

### DECLARATIONS ###

	if [[ -z $1 ]]; then
		echo "Missing argument: path to libft directory"
		exit 1
	else
		DIR=$1
		cd $DIR
		DIR=$(pwd)
		cd -
		pwd
	fi

	if [[ -e $DIR/norminette.txt ]]; then
		rm -f norminette.txt
	fi

	make fclean -C $DIR >/dev/null 2>/dev/null

	OS=$(uname)
	NAME=libft.a
	NORM_LOG=norminette.txt

	# Colors
	RED="\033[0;31m"
	GRN="\033[0;32m"
	YEL="\033[0;33m"
	BLU="\033[0;34m"
	CYN="\033[0;36m"
	# Reset
	CRESET="\033[0m"

	FORBIDDEN=(
		isalpha isdigit isalnum isascii isprint islower isupper
		toupper tolower
		strlen
		strtrim
		memchr
		strchr strrchr strstr strnstr
		memcpy memmove
		strcpy strncpy strlcpy strdup
		substr
		strcat strncat strlcat strjoin
		memcmp
		strcmp strncmp
		memset bzero
		atoi atoi strtol
		calloc realloc
		printf dprintf sprintf snprintf puts
		open read close fopen fread fclose
		main exit
	)

	ALLOWED=(
		malloc free write
	)

	REQUIRED_FUNCS=(
		isalpha isdigit isalnum isascii isprint
		toupper tolower
		strlen
		memchr
		strchr strrchr
		strnstr
		memcmp
		strncmp
		memcpy memmove
		strlcpy strlcat
		strdup
		substr
		memset
		bzero
		calloc
		strjoin strtrim
		split
		putchar_fd putnbr_fd putstr_fd putendl_fd
		striteri strmapi
		lstnew lstdelone
		lstsize lstlast
		#TODO
		lstadd_front lstadd_back
		lstclear
		lstiter lstmap
	)

	REQUIRED_FILES=(
		Makefile libft.h README.md
	)

	FILES=$(find $DIR ! -path "*/.git/*" ! -name ".git*")

	ERROR=0
	COUNT=0

### PROGRAM ###

	clear
	echo -en $CYN
	cat << 'EOF'

 ,dPYb,       ,dPYb,      ,dPYb,    I8
 IP'`Yb       IP'`Yb      IP'`Yb    I8
 I8  8I  gg   I8  8I      I8  8I 88888888
 I8  8'  ""   I8  8'      I8  8'    I8
 I8 dP   gg   I8 dP       I8 dP     I8
 I8dP    88   I8dP   88gg I8dP      I8
 I8P     88   I8P    8I   I8P      ,I8,
,d8b,_ _,88,_,d8b,  ,8I  ,d8b,_   ,d88b,
8P'"Y888P""Y88P'"Y88P"'  PI8"888888P""Y88
                          I8 `8,
                          I8  `8,
                          I8   8I
                          I8   8I
                          I8, ,8'
                           "Y8P'
EOF
	echo "checker by jepiscic@42"
	echo -e $CRESET

	echo -e Working directory: $DIR"\\n"

	echo -e "$BLU"CHECKING FILE NAMES"$CRESET"

### CHECKING REQUIRED FILES ###

	ERROR=0
	for f in ${REQUIRED_FILES[@]}; do
		if ! [[ ${FILES[*]} =~ $DIR/$f ]]; then
			((ERROR+=1))
			((COUNT+=1))
			echo -e $f "$RED"not found"$CRESET"
		fi
	done

	echo -n "====> "

	if [[ $ERROR == 0 ]]; then
		echo -e "$GRN"Required files OK"$CRESET"
	elif [[ $ERROR == 1 ]]; then
		echo -e "$RED"$ERROR required file not found"$CRESET"
	else
		echo -e "$RED"$ERROR required files not found"$CRESET"
	fi


### CHECKING FILE NAMES ###

	ERROR=0
	for f in ${FILES[@]}; do
		f=$(basename "$f")
		if ! [[ ${REQUIRED_FILES[*]} =~ $f ]] && ! [[ $f =~ ^ft_.*\.c$ ]]; then
			((ERROR+=1))
			((COUNT+=1))
			echo -e $f: "$RED"invalid file or directory"$CRESET"
		fi
	done

	echo -n "====> "

	if [[ $ERROR == 0 ]]; then
		echo -e "$GRN"File names OK"$CRESET"
	elif [[ $ERROR == 1 ]]; then
		echo -e "$RED"$ERROR invalid file name"$CRESET"
	else
		echo -e "$RED"$ERROR invalid file names"$CRESET"
	fi

	echo ""

### NORM ###

	echo -e "$BLU"CHECKING NORM"$CRESET"

	norminette "$DIR" | grep Error > "$NORM_LOG"

	if ! [[ -s $NORM_LOG ]]; then
		echo -e "====> ""$GRN"Norm OK"$CRESET"
	else
		cat "$NORM_LOG"
		((COUNT += 1))
	fi

	rm -f "$NORM_LOG"

	echo ""


### MAKEFILE ###

	echo -e "$BLU"CHECKING MAKEFILE"$CRESET"

	ERROR=0

	for m in "" clean fclean all "$NAME" re; do
		make "$m" -C $DIR >/dev/null 2>/dev/null
		echo -en make "$m "
		if [[ $? == 0 ]]; then
			echo -e "$GRN"OK"$CRESET"
		else
			echo -e "$RED"KO"$CRESET"
			((COUNT += 1))
			((ERROR += 1))
		fi
	done

	if [[ -z $DIR/$NAME ]]; then
		echo -e "$RED"Error"$CRESET": $NAME not found
		((COUNT += 1))
		((ERROR += 1))
	fi

	if [[ $ERROR == 0 ]]; then
		echo -e "====> $GRN"Makefile OK"$CRESET"
	fi

	echo ""


### CHECKING FUNCTIONS ###

	echo -e "$BLU"LOOKING UP FUNCTIONS"$CRESET"
	if [[ $OS = "Linux" ]]; then
		FUNC=$(nm -j "$DIR/$NAME" | grep -v -E "\.|__" | sort | uniq)
	else
		FUNC=$(nm "$DIR/$NAME" | grep -E " _[a-z]" | grep -E .+ | cut -d _ -f 2- | sort | uniq)
	fi


##### REQUIRED FUNCTIONS #####

	ERROR=0
	CATH=$(cat $DIR/libft.h | grep -v "/\**\/" | grep -v "//")

	for f in ${REQUIRED_FUNCS[@]}; do
		if [[ ${FUNC[*]} =~ $f ]]; then
			echo -e $f "$GRN"OK"$CRESET"
			if ! [[ ${CATH} =~ $f ]]; then
				echo -e $f "$YEL"but not in libft.h"$CRESET"
			fi
		else
			echo -e $f "$RED"KO"$CRESET"
			((ERROR+=1))
			((COUNT+=1))
		fi
	done

	echo -n "====> "

	if [[ $ERROR == 0 ]]; then
		echo -e "$GRN"Required functions OK"$CRESET"
	elif [[ $ERROR == 1 ]]; then
		echo -e "$RED"$ERROR required function not found"$CRESET"
	else
		echo -e "$RED"$ERROR required function not found"$CRESET"
	fi

##### FORBIDDEN FUNCTIONS #####

	ERROR=0
	for f in ${FUNC[@]}; do
		if [[ ${FORBIDDEN[*]} =~ $f ]]; then
			echo -e "$RED"Use of forbidden function"$CRESET": $f
			((ERROR += 1))
			((COUNT += 1))
		fi
	done

	if [[ -e "$NAME" ]]; then
		echo -n "====> "
		if [[ $ERROR == 0 ]]; then
			echo -e "$GRN"No forbidden function found"$CRESET"
		elif [[ $ERROR == 1 ]]; then
			echo -e "$RED"$ERROR forbidden function found"$CRESET"
		else
			echo -e "$RED"$ERROR forbidden functions found"$CRESET"
		fi
	fi

	echo ""

	make fclean -C $DIR >/dev/null 2>/dev/null

### TEST FUNCTIONS ###

	echo -e "$BLU"TESTING FUNCTIONS"$CRESET"

	curl -fsS -L -o jepiscic.zip \
			https://github.com/Jecapitch/42_projects/archive/refs/heads/main.zip
	unzip jepiscic.zip > /dev/null
	rm -f jepiscic
	rsync -a --delete $(ls | grep 42_projects)/tests/libft_tester .
	rm -rf 42_projects*
	cd libft_tester

	mkdir -p traces

	NON_STD=(
		strjoin strtrim
		split
		striteri strmapi
		lstsize lstlast
		lstnew lstadd_front lstadd_back
		lstdelone lstclear
		lstiter lstmap
	)

	PRINT=(
		putchar_fd putnbr_fd putstr_fd putendl_fd
	)

	make libclean LIBFT=$DIR

	for FUNC in ${REQUIRED_FUNCS[@]}; do
		if [[ $FUNC =~ ^is|to ]]; then
			FILENAME=charcheck
		elif [[ $FUNC =~ len ]]; then
			FILENAME=strlen
		elif [[ $FUNC =~ set ]]; then
			FILENAME=memset
		elif [[ $FUNC =~ bz ]]; then
			FILENAME=bzero
		elif [[ $FUNC =~ alloc ]]; then
			FILENAME=calloc
		elif [[ $FUNC =~ strr?chr ]]; then
			FILENAME=strchr
		elif [[ $FUNC =~ chr ]]; then
			FILENAME=memchr
		elif [[ $FUNC =~ cmp ]]; then
			FILENAME=cmp
		elif [[ $FUNC =~ strlc ]]; then
			FILENAME=strl
		elif [[ $FUNC =~ cpy|move ]] ; then
			FILENAME=memcpy
		elif [[ $FUNC =~ dup ]]; then
			FILENAME=strdup
		elif [[ $FUNC =~ subs ]]; then
			FILENAME=substr
		elif [[ $FUNC =~ join|trim ]]; then
			FILENAME=jointrim
		elif [[ $FUNC =~ split ]]; then
			FILENAME=split
		elif [[ $FUNC =~ put(s|e) ]]; then
			FILENAME=puts
		elif [[ $FUNC =~ put(n|c) ]]; then
			FILENAME=putd
		elif [[ $FUNC =~ striter ]]; then
			FILENAME=striter
		elif [[ $FUNC =~ strmap ]]; then
			FILENAME=strmap
		elif [[ $FUNC =~ lstnew ]]; then
			FILENAME=lstnew
		elif [[ $FUNC =~ lstdel ]]; then
			FILENAME=lstdelone
		elif [[ $FUNC =~ size ]]; then
			FILENAME=lstsize
		elif [[ $FUNC =~ last ]]; then
			FILENAME=lstlast
		else
			continue
		fi

		FT=ft_$FUNC
		if [[ ${NON_STD[*]} =~ $FUNC ]]; then
			STD=tester_ft_$FUNC
		elif [[ ${PRINT[*]} =~ $FUNC ]]; then
			STD=dprintf
		else
			STD=$FUNC
		fi

		make FILE=$FILENAME FT=$FT STD=$STD LIBFT=$DIR
		./${FT}_test
		ERROR=$?
		if [[ $FUNC =~ put ]]; then
			USER_OUTPUT="traces/${FT}_user_output"
			TEST_OUTPUT="traces/${FT}_test_output"
			TRACE="traces/trace_$FUNC"
			diff -C 3 <(cat -e "$USER_OUTPUT") <(cat -e $TEST_OUTPUT) > $TRACE
			(( ERROR += $? ))
		fi
		make fclean FILE=$FILENAME FT=$FT STD=$STD LIBFT=$DIR
		echo -en $CYN"====>"$CRESET "ft_$FUNC  \\t"
		[[ $ERROR == 0 ]] \
			&& echo -e $GRN"OK"$CRESET \
			|| { echo -e $RED"KO\\n"$CRESET ; ((COUNT += 1)); }
	done

	make libclean LIBFT=$DIR

	echo ""


### RESULT ###

	echo -e "$BLU"RESULT"$CRESET"

	if [[ $COUNT == 0 ]]; then
		echo -e "$GRN"$NAME OK"$CRESET"
	elif [[ $COUNT == 1 ]]; then
		echo -e "$RED"$COUNT error: $NAME KO"$CRESET"
	else
		echo -e "$RED"$COUNT errors: $NAME KO"$CRESET"
	fi

	echo ""
	echo -e "$RED"DISCLAIMER"$CRESET"
	cat << EOF
• Don't trust this tester. It can be wrong. Always double check. Run your own tests.
• Memory leaks aren't tracked. Good luck. Don't panic.

EOF
