#!/bin/bash

RES=0

	# Colors
	BRED="\033[1;31m"
	BGRN="\033[1;32m"
	BYEL="\033[1;33m"
	BBLU="\033[1;34m"
	BCYN="\033[1;36m"
	# Reset
	CRESET="\033[0m"

REQUIRED_FUNCS=(
isalpha isdigit isalnum isascii isprint toupper tolower
strlen
memchr
strchr strrchr
strnstr
memcmp
strncmp
memcpy memmove
strlcpy strlcat
strdup
substr
memset
bzero
calloc
strjoin strtrim
#TODO
split
strmapi striteri
lstsize lstlast
lstnew lstadd_front lstadd_back
lstdelone lstclear
lstiter lstmap
)

NONSTD=(
strjoin strtrim
split
strmapi striteri
lstsize lstlast
lstnew lstadd_front lstadd_back
lstdelone lstclear
lstiter lstmap
)

make libclean

for FUNC in ${REQUIRED_FUNCS[@]}; do
	if [[ $FUNC =~ ^is|to ]]; then
		FILENAME=charcheck
	elif [[ $FUNC =~ len ]]; then
		FILENAME=strlen
	elif [[ $FUNC =~ set ]]; then
		FILENAME=memset
	elif [[ $FUNC =~ bz ]]; then
		FILENAME=bzero
	elif [[ $FUNC =~ alloc ]]; then
		FILENAME=calloc
	elif [[ $FUNC =~ strr?chr ]]; then
		FILENAME=strchr
	elif [[ $FUNC =~ chr ]]; then
		FILENAME=memchr
	elif [[ $FUNC =~ cmp ]]; then
		FILENAME=cmp
	elif [[ $FUNC =~ strlc ]]; then
		FILENAME=strl
	elif [[ $FUNC =~ cpy|move ]] ; then
		FILENAME=memcpy
	elif [[ $FUNC =~ dup ]]; then
		FILENAME=strdup
	elif [[ $FUNC =~ subs ]]; then
		FILENAME=substr
	elif [[ $FUNC =~ join|trim ]]; then
		FILENAME=jointrim
	else
		continue
	fi

	FT=ft_$FUNC
	if [[ ${NONSTD[*]} =~ $FUNC ]]; then
		STD=tester_ft_$FUNC
	else
		STD=$FUNC
	fi

	make FILE=$FILENAME FT=$FT STD=$STD
	./${FT}_test
	ERROR=$?
	make fclean FILE=$FILENAME FT=$FT STD=$STD
	echo -en $BCYN"====>"$CRESET "ft_$FUNC  \\t"
	[[ $ERROR == 0 ]] \
		&& echo -e $BGRN"OK"$CRESET \
		|| { echo -e $BRED"KO\\n"$CRESET ; ((RES += 1)); }
done

make libclean

echo -e $BCYN"======================="$CRESET
echo -n "# libft "
[[ $RES == 0 ]] \
	&& echo -e $BGRN"OK"$CRESET \
	|| echo -e $BRED"KO"$CRESET "($RES failed)"
echo ""
